/* Generated by scripts/images.mjs. Do not edit by hand. */
export const imageSets: Record<string, { avif: string; webp: string }> = {
  "/assets/images/hero-adryan.webp": {
    "avif": "/assets/images/opt/hero-adryan-640.avif 640w, /assets/images/opt/hero-adryan-960.avif 960w, /assets/images/opt/hero-adryan-1280.avif 1280w, /assets/images/opt/hero-adryan-1600.avif 1600w, /assets/images/opt/hero-adryan-2000.avif 2000w",
    "webp": "/assets/images/opt/hero-adryan-640.webp 640w, /assets/images/opt/hero-adryan-960.webp 960w, /assets/images/opt/hero-adryan-1280.webp 1280w, /assets/images/opt/hero-adryan-1600.webp 1600w, /assets/images/opt/hero-adryan-2000.webp 2000w"
  },
  "/assets/images/about-adryan.webp": {
    "avif": "/assets/images/opt/about-adryan-480.avif 480w, /assets/images/opt/about-adryan-800.avif 800w, /assets/images/opt/about-adryan-1100.avif 1100w, /assets/images/opt/about-adryan-1600.avif 1600w",
    "webp": "/assets/images/opt/about-adryan-480.webp 480w, /assets/images/opt/about-adryan-800.webp 800w, /assets/images/opt/about-adryan-1100.webp 1100w, /assets/images/opt/about-adryan-1600.webp 1600w"
  },
  "/assets/images/project-01-cover.webp": {
    "avif": "/assets/images/opt/project-01-cover-640.avif 640w, /assets/images/opt/project-01-cover-960.avif 960w, /assets/images/opt/project-01-cover-1280.avif 1280w, /assets/images/opt/project-01-cover-1920.avif 1920w",
    "webp": "/assets/images/opt/project-01-cover-640.webp 640w, /assets/images/opt/project-01-cover-960.webp 960w, /assets/images/opt/project-01-cover-1280.webp 1280w, /assets/images/opt/project-01-cover-1920.webp 1920w"
  },
  "/assets/images/project-01-detail.webp": {
    "avif": "/assets/images/opt/project-01-detail-480.avif 480w, /assets/images/opt/project-01-detail-800.avif 800w, /assets/images/opt/project-01-detail-1200.avif 1200w, /assets/images/opt/project-01-detail-1600.avif 1600w",
    "webp": "/assets/images/opt/project-01-detail-480.webp 480w, /assets/images/opt/project-01-detail-800.webp 800w, /assets/images/opt/project-01-detail-1200.webp 1200w, /assets/images/opt/project-01-detail-1600.webp 1600w"
  },
  "/assets/images/project-02-cover.webp": {
    "avif": "/assets/images/opt/project-02-cover-640.avif 640w, /assets/images/opt/project-02-cover-960.avif 960w, /assets/images/opt/project-02-cover-1280.avif 1280w, /assets/images/opt/project-02-cover-1920.avif 1920w",
    "webp": "/assets/images/opt/project-02-cover-640.webp 640w, /assets/images/opt/project-02-cover-960.webp 960w, /assets/images/opt/project-02-cover-1280.webp 1280w, /assets/images/opt/project-02-cover-1920.webp 1920w"
  },
  "/assets/images/project-02-detail.webp": {
    "avif": "/assets/images/opt/project-02-detail-480.avif 480w, /assets/images/opt/project-02-detail-800.avif 800w, /assets/images/opt/project-02-detail-1200.avif 1200w, /assets/images/opt/project-02-detail-1600.avif 1600w",
    "webp": "/assets/images/opt/project-02-detail-480.webp 480w, /assets/images/opt/project-02-detail-800.webp 800w, /assets/images/opt/project-02-detail-1200.webp 1200w, /assets/images/opt/project-02-detail-1600.webp 1600w"
  },
  "/assets/images/project-03-cover.webp": {
    "avif": "/assets/images/opt/project-03-cover-640.avif 640w, /assets/images/opt/project-03-cover-960.avif 960w, /assets/images/opt/project-03-cover-1280.avif 1280w, /assets/images/opt/project-03-cover-1920.avif 1920w",
    "webp": "/assets/images/opt/project-03-cover-640.webp 640w, /assets/images/opt/project-03-cover-960.webp 960w, /assets/images/opt/project-03-cover-1280.webp 1280w, /assets/images/opt/project-03-cover-1920.webp 1920w"
  },
  "/assets/images/project-03-mobile.webp": {
    "avif": "/assets/images/opt/project-03-mobile-480.avif 480w, /assets/images/opt/project-03-mobile-720.avif 720w, /assets/images/opt/project-03-mobile-1000.avif 1000w",
    "webp": "/assets/images/opt/project-03-mobile-480.webp 480w, /assets/images/opt/project-03-mobile-720.webp 720w, /assets/images/opt/project-03-mobile-1000.webp 1000w"
  },
  "/assets/images/project-04-cover.webp": {
    "avif": "/assets/images/opt/project-04-cover-640.avif 640w, /assets/images/opt/project-04-cover-960.avif 960w, /assets/images/opt/project-04-cover-1280.avif 1280w, /assets/images/opt/project-04-cover-1920.avif 1920w",
    "webp": "/assets/images/opt/project-04-cover-640.webp 640w, /assets/images/opt/project-04-cover-960.webp 960w, /assets/images/opt/project-04-cover-1280.webp 1280w, /assets/images/opt/project-04-cover-1920.webp 1920w"
  },
  "/assets/images/project-04-detail.webp": {
    "avif": "/assets/images/opt/project-04-detail-480.avif 480w, /assets/images/opt/project-04-detail-800.avif 800w, /assets/images/opt/project-04-detail-1200.avif 1200w, /assets/images/opt/project-04-detail-1600.avif 1600w",
    "webp": "/assets/images/opt/project-04-detail-480.webp 480w, /assets/images/opt/project-04-detail-800.webp 800w, /assets/images/opt/project-04-detail-1200.webp 1200w, /assets/images/opt/project-04-detail-1600.webp 1600w"
  }
}
