import { mkdir, writeFile } from 'node:fs/promises'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import sharp from 'sharp'

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..')
const sourceDir = path.join(root, 'public/assets/images')
const outDir = path.join(sourceDir, 'opt')

const jobs = [
  { file: 'hero-adryan.webp', widths: [640, 960, 1280, 1600, 2000] },
  { file: 'about-adryan.webp', widths: [480, 800, 1100, 1600] },
  { file: 'project-01-cover.webp', widths: [640, 960, 1280, 1920] },
  { file: 'project-01-detail.webp', widths: [480, 800, 1200, 1600] },
  { file: 'project-02-cover.webp', widths: [640, 960, 1280, 1920] },
  { file: 'project-02-detail.webp', widths: [480, 800, 1200, 1600] },
  { file: 'project-03-cover.webp', widths: [640, 960, 1280, 1920] },
  { file: 'project-03-mobile.webp', widths: [480, 720, 1000] },
  { file: 'project-04-cover.webp', widths: [640, 960, 1280, 1920] },
  { file: 'project-04-detail.webp', widths: [480, 800, 1200, 1600] },
]

await mkdir(outDir, { recursive: true })

/** @type {Record<string, { avif: string, webp: string }>} */
const sets = {}

for (const job of jobs) {
  const input = path.join(sourceDir, job.file)
  const meta = await sharp(input).metadata()
  const limit = meta.width ?? job.widths[job.widths.length - 1]
  const widths = [...new Set(job.widths.filter((width) => width <= limit))]
  if (!widths.includes(limit)) widths.push(limit)
  widths.sort((a, b) => a - b)

  const avif = []
  const webp = []
  const stem = job.file.replace(/\.webp$/, '')

  for (const width of widths) {
    const base = `${stem}-${width}`
    const pipeline = sharp(input).resize({ width, withoutEnlargement: true })
    await Promise.all([
      pipeline.clone().avif({ quality: 48, effort: 4 }).toFile(path.join(outDir, `${base}.avif`)),
      pipeline.clone().webp({ quality: 70 }).toFile(path.join(outDir, `${base}.webp`)),
    ])
    avif.push(`/assets/images/opt/${base}.avif ${width}w`)
    webp.push(`/assets/images/opt/${base}.webp ${width}w`)
  }

  sets[`/assets/images/${job.file}`] = {
    avif: avif.join(', '),
    webp: webp.join(', '),
  }
  console.log(`${job.file} → ${widths.join(', ')}`)
}

const body = `/* Generated by scripts/images.mjs. Do not edit by hand. */
export const imageSets: Record<string, { avif: string; webp: string }> = ${JSON.stringify(sets, null, 2)}
`

await writeFile(path.join(root, 'src/data/imageSets.ts'), body)
console.log('wrote src/data/imageSets.ts')
